# Generated by Django 4.2.4 on 2023-09-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of project', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='date and time project created')),
            ],
        ),
    ]
