# Generated by Django 4.2.4 on 2023-09-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectp', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(help_text='date and time project created', null=True),
        ),
    ]
